mat = BlockMatrix(2, 3)
pr, l, u, pc = mat.get_lu()
print(pr.toarray())
print()
print(mat.data.toarray())
print()
print(pc.toarray())
print()
print(l.toarray())
print()
print(u.toarray())
print()
# re = mat.test_lu(pr, l, u, pc)
# print(re.toarray())
nnz, nz, rel_nnz, rel_nz = mat.eval_zeros_lu()
print("{}, {}, {}, {}".format(nnz, nz, rel_nnz, rel_nz))
print(mat.get_cond())

#draw_cond(10)
draw_nonzero(10)
